### ISSUE TITLE
Incorrect query results

### ISSUE THREAD

**Issue by zstadler** [drolbr/Overpass-API#297] opened 2016-07-19 13:12 UTC
The [following query](http://overpass-turbo.eu/s/hna) is looking for ways in a given area that have some tag with a `proposed` value but with no values for the `proposed` tag:
```
[timeout:3600];
way
  // Something is proposed
  [~"."~"proposed"]
  // and proposed is empty
  ["proposed"!~"."]
  (area:3601473946)
  ;
out meta geom;
out count;
```
However, the query results include ways with a value to the proposed tag.
For example, [way 402479802](http://www.openstreetmap.org/way/402479802):
```
Way 402479802
Tags:
    highway=proposed
    note=please do not change the tag : highway=proposed to something else, till the road is opened and a car can drive on it.
    note1=According to plan ד/631
    oneway=yes
    proposed=trunk
    ref=36 or 360
```

[Searching using a bounding box](http://overpass-turbo.eu/s/hnb) seem to avoid the issue:
  ```
[timeout:3600];
way
  // Something is proposed
  [~"."~"proposed"]
  // and proposed is empty
  ["proposed"!~"."]
  // bbox taken from way 402479802 meta data 
  (31.7356138, 34.6787249, 31.7688892, 34.6895048)
  ;
out meta geom;
out count;
```

**Comment by mmd-osm** [comment] 2016-07-19 13:42
That's very likely a duplicate of https://github.com/drolbr/Overpass-API/issues/192

**Comment by mmd-osm** [comment] 2016-07-19 19:57
Initially, I thought this is a duplicate of #192, but even with that fix in place, the issue can be reproduced.

It seems that is doesn't matter, if areas or bboxes are used to restrict the query. I could reproduce the issue with the following bbox on the dev instance:
(31.11526731701526,34.146881103515625,32.204667362701414,35.760498046875)

**Comment by mmd-osm** [comment] 2016-07-20 21:25
Issue is similar to #192. Both methods collect_ids return duplicate values, which doesn't really work with `diff_ids.erase(set_difference(id_idxs.begin(), id_idxs.end(), non_ids.begin(), non_ids.end(),
		     diff_ids.begin()), diff_ids.end());`

In collect_non_ids, duplicates are already removed. Adding the same to collect_ids at least fixes the incorrect result above. Side effects tbc...

```
diff --git a/src/overpass_api/statements/query.cc b/src/overpass_api/statements/query.cc
index e75b236..ca38aaa 100644
--- a/src/overpass_api/statements/query.cc
+++ b/src/overpass_api/statements/query.cc
@@ -300,6 +300,10 @@ std::vector< std::pair< Id_Type, Uint31_Index > > Query_Statement::collect_ids
     }
   }
 
+ // remove duplicates
+  sort(new_ids.begin(), new_ids.end());
+  new_ids.erase(unique(new_ids.begin(), new_ids.end()), new_ids.end());
+
   return new_ids;
 }
 
@@ -366,6 +370,10 @@ vector< Id_Type > Query_Statement::collect_ids
     }
   }
 
+  // remove duplicates
+  sort(new_ids.begin(), new_ids.end());
+  new_ids.erase(unique(new_ids.begin(), new_ids.end()), new_ids.end());
+
   return new_ids;
 }
```

**Comment by drolbr** [comment] 2016-07-27 03:59
I haven't looked into the pull requests yet. `collect_ids` is indeed supposed to deliver a unique list of elements. And that problem would completely explain the incorrect results, because query chooses a different strategy on small bounding boxes.

**Comment by mmd-osm** [comment] 2016-08-28 16:55
This issue can be closed, fix was merged in https://github.com/drolbr/Overpass-API/pull/299

**Closed** 2016-08-28 20:36 UTC
Labels: bug

**Comment by mmd-osm** [comment] 2016-09-22 10:46
@zstadler : you can test this on the **French instance** now (http://api.openstreetmap.fr/oapi/)

**Comment by zstadler** [comment] 2016-09-22 21:47
@mmd-osm Works like charm. Thanks!
