### ISSUE TITLE
Multi-core planet import

### ISSUE THREAD

**Issue by WebstudioThomHubers** [drolbr/Overpass-API#344] opened 2016-12-08 20:49 UTC
It takes hours to import the planet files, even on a big Azure instance. The CPU seems to be the bottleneck. Would it be possible to make this multi-core?

**Comment by mmd-osm** [comment] 2016-12-08 21:22
Duplicate of https://github.com/drolbr/Overpass-API/issues/281 / https://github.com/drolbr/Overpass-API/issues/307

In the meantime, you can use the clone based process as described in the documentation http://overpass-api.de/no_frills.html -> Fast startup.

**Comment by mmd-osm** [comment] 2016-12-11 16:25
@WebstudioThomHubers : if this answers your question, would you be so kind and close this issue? We will do a follow up in the two issues I mentioned anyway. Thanks.

**Closed** 2016-12-12 18:07 UTC
