### ISSUE TITLE
HTTP status for timeouts

### ISSUE THREAD

**Issue by repomaa** [drolbr/Overpass-API#577] opened 2020-06-01 14:56 UTC
Timeouted queries misleadingly return 200 - OK as a HTTP status. IMO this should be 504 or maybe 413 to indicate a client error (since the client can amp up the timeout).

**Comment by mmd-osm** [comment] 2020-06-01 15:06
That’s a duplicate of #94 and by design. Please close the issue if this answers your question.

**Closed** 2020-07-10 23:39 UTC

**Comment by matkoniecz** [comment] 2021-06-09 07:14
Is it safe to assume that `remark` will be present in 200 code responses iff error happened?
