### ISSUE TITLE
node_tags_global.bin.idx File_Blocks_Index: Unsupported index file format version

### ISSUE THREAD

**Issue by KidA001** [drolbr/Overpass-API#548] opened 2019-12-11 08:18 UTC
Apologies if this is not the right place for this issue.
I'm trying to create a local working copy of OSM. I'm following the instructions here: http://overpass-api.de/no_frills.html

I've successfully made it through all the steps...downloading files, make install, cloning the DB...etc.  When I start osm_query `sudo $EXEC_DIR/bin/osm3s_query --db-dir=$DB_DIR` and run a query,  I get an error `runtime error: open64: /mnt/disks/osm-db-disk/osm-db/node_tags_global.bin.idx File_Blocks_Index: Unsupported index file format version`.

I thought my database files might be corrupt, so I wiped and started the download script again
`bin/download_clone.sh --source=https://dev.overpass-api.de/api_drolbr/ --db-dir=$DB_DIR --meta=no ` however I'm still getting the same error. Full output below
```
encoding remark: Please enter your query and terminate it with CTRL+D.
<query type="node"><bbox-query n="51.0" s="50.9" w="6.9" e="7.0"/><has-kv k="amenity" v="pub"/></query><print/>
encoding remark: Your input starts with a tag but not the root tag. Thus, a line with the
datatype declaration and a line with the root tag 'osm-script' is
added. This shifts line numbering by -2 line(s).
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.55.7 8b86ff77">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base=""/>


</osm>
runtime error: open64: /mnt/disks/osm-db-disk/osm-db/node_tags_global.bin.idx File_Blocks_Index: Unsupported index file format version
```

**Version:**
Ubuntu 14.04
osm-3s_v0.7.55

Any help appreciated

**Comment by mmd-osm** [comment] 2019-12-11 08:35
Also reported on https://gis.stackexchange.com/questions/344650/error-node-tags-global-bin-idx-file-blocks-index-unsupported-index-file-format

**Comment by KidA001** [comment] 2019-12-11 08:57
An update, I re-installed osm-3s_v0.7.55 - When I run a query I don't get any errors, I just get an empty response. What am I missing?

Output
```bash
root@osm-database-vm:/home/ubuntu/osm_install_files# sudo $EXEC_DIR/bin/osm3s_query --db-dir=$DB_DIR
encoding remark: Please enter your query and terminate it with CTRL+D.
<query type="node"><bbox-query n="51.0" s="50.9" w="6.9" e="7.0"/><has-kv k="amenity" v="pub"/></query><print/>

encoding remark: Your input starts with a tag but not the root tag. Thus, a line with the
datatype declaration and a line with the root tag 'osm-script' is
added. This shifts line numbering by -2 line(s).
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.55.7 8b86ff77">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base=""/>


</osm>
root@osm-database-vm:/home/ubuntu/osm_install_files#
```

**Comment by mmd-osm** [comment] 2019-12-11 08:59
First of all, never run any of the Overpass binaries as root, this is strongly discouraged and not supported.

**Comment by mmd-osm** [comment] 2019-12-11 09:01
As this seems to be more of a howto issue at this time, I think it would be best if you could follow up on https://listes.openstreetmap.fr/wws/info/overpass and close this Github issue for the time being.

**Comment by KidA001** [comment] 2019-12-11 17:19
@mmd-osm  I don't actually know that it's a how-to issue? Is running this as root the cause of the problem, or is it just discouraged? I've followed all the instructions step by step, but do not get any query data back. What might I be missing?

**Comment by mmd-osm** [comment] 2019-12-11 17:45
> Is running this as root the cause of the problem, or is it just discouraged?

The wiki has a quite clear position on that one: https://wiki.openstreetmap.org/wiki/Overpass_API/Installation:

- Never start any component of Overpass API as root. The whole system is designed to work without root, and **you can run into really weird bugs if some parts of the system run as root**.
- Do not automatically remove any of the lock files, socket files or shared memory files. They work as canaries, i.e. hitting existing files is almost always an indicator for bigger trouble elsewhere. Please ask back in those cases.

I don't know if this the root cause for your issue, it's just something I wanted to raise your awareness for, before trying anything else.

**Comment by mmd-osm** [comment] 2019-12-11 17:47
Also, it would be good if you could describe your set up a bit, system environment, if you're running a dispatcher, ... that's why I recommended the dev mailing list, where more sysops successfully running an Overpass server are around. We use Github for bug reports and enhancement requests mainly.

**Comment by KidA001** [comment] 2019-12-11 17:52
@mmd-osm I just emailed the list but it's very unclear to me if it went through as I didn't get a copy. Maybe you can confirm? Mailing lists are a bit before my time :)

I'm running a Virtual Machine on google cloud with Ubuntu 14.04 and osm-3s_v0.7.55 - I'm not running a dispatcher, I ran through all the instructions and am now at the point of using osm3_query `$EXEC_DIR/bin/osm3s_query --db-dir=$DB_DIR`

**Comment by mmd-osm** [comment] 2019-12-11 17:57
I can see your post in the archive: https://listes.openstreetmap.fr/wws/arc/overpass/2019-12/msg00000.html :+1: 

By the way, could you maybe post the date of your database files, or the  replicate_id file contents? Maybe there was some issue downloading the files, and I can provide some md5sum or sha1sum checksum for some of the files.

**Comment by KidA001** [comment] 2019-12-11 18:14
@mmd-osm  Really appreciate your help, thank you.

Replicate id is `3795685` - a checksum would be great. My `base_url` shows 12/10 but I thought I had 12/11 database files. Hopefully the replicate_id solves that.

**Comment by mmd-osm** [comment] 2019-12-11 18:19
Right, your replicate id corresponds to the 2019-12-10 download directory.

I'm posting the respective sha1sum for the idx files first, as the other files take quite some time to process:

```
sha1sum *.idx
6f6c1f390f3f1abed1339b03a83805e395f29175  node_attic_indexes.bin.idx
5138a93440a033df5176048a61bb8633de4f05e7  node_changelog.bin.idx
68212bacd578dabc8956aac564a44c28896d39f9  node_keys.bin.idx
dc770b4d8b4b993bbbcddce203f4510d23aa1eed  nodes_attic.bin.idx
fbcb6d74a5feb3c37e16eae1b0cc7e77ade75984  nodes_attic.map.idx
ab10ea555462dfbcda540b13411424344d9f51a1  nodes_attic_undeleted.bin.idx
c003c4560b3e84a8be17187d0f2253b6e800e146  nodes.bin.idx
af1c50663b27c90e66196e6196504d984ae56370  nodes.map.idx
be1ddd1a6609518274b0ae81e77c7776f6be3dbc  nodes_meta_attic.bin.idx
0573cf1ffebaaf769639fdde9812e85c9a0224ca  nodes_meta.bin.idx
4d3346837c2cf65f02e67f1ccd65e9d8d510157e  node_tags_global_attic.bin.idx
3b8d0a0d4c847924590219370ee88822405e6756  node_tags_global.bin.idx
d888ca0e098f0a2a002b41523894714c0b80214b  node_tags_local_attic.bin.idx
d8a26029bdf948d1d4ce74eae17486fb7b245901  node_tags_local.bin.idx
56f7de8ecccaba2f51ca6a456468c9fb764abfab  relation_attic_indexes.bin.idx
cbf61a9286dc0d178a2f93e4e09897d33149e28e  relation_changelog.bin.idx
77328bfbc493d1aa6e3e9eef3264aa85a944583f  relation_keys.bin.idx
3745d06d6da1c9836421ced24bef3f857b4f9f31  relation_roles.bin.idx
3a6affcf774edf9a4ebf5c4b427ec3f0aa40548e  relations_attic.bin.idx
cf3ed2797ed3a87cde1f300559c375ee8dbebb2d  relations_attic.map.idx
49720900f46cc4f298b0aa683e5395bd11fc831e  relations_attic_undeleted.bin.idx
f1d8bc0c5c061b35b906aa3c188b5f2356204972  relations.bin.idx
cf3ed2797ed3a87cde1f300559c375ee8dbebb2d  relations.map.idx
3c5a341d11afb513df17e90181b3444f619f8612  relations_meta_attic.bin.idx
ae3b218f70e54a8a6c13a303b1909047191d06ac  relations_meta.bin.idx
83a2ff71ee426680b11dd6b3f966d2a1310d3f57  relation_tags_global_attic.bin.idx
dbdef1dc4df74cd7a89f9fc6aaec87428ca171b3  relation_tags_global.bin.idx
c7191bca3dafc09dbaec91b393bb180f8559097e  relation_tags_local_attic.bin.idx
bf6c48570b0cda7141005e9d30bf1274884e4e30  relation_tags_local.bin.idx
f2d34030ca2eb9518152b48fbb2faa19eb05939f  user_data.bin.idx
5f6ff03d7ce4f786939a55fadbb45b8e3f8d4886  user_indices.bin.idx
e1cf809f5e21c5525e2b907c531d4c9d46d1e4de  way_attic_indexes.bin.idx
c11cf7d0706d9e5634a139edef0d052079205a4c  way_changelog.bin.idx
0e10f09331043971f2526d91fec0dceccd67a51b  way_keys.bin.idx
c7e9e110c8fa1ea60582402174445cb8595e3d37  ways_attic.bin.idx
3b8794c432d1857edc4e2fffa57141f818b3a978  ways_attic.map.idx
50eb9109423b9dcfdf6f8fca2075247bfa3b2cba  ways_attic_undeleted.bin.idx
1163aae287b0306cdd5590cb2bfb9bb21ce94c27  ways.bin.idx
3b8794c432d1857edc4e2fffa57141f818b3a978  ways.map.idx
8d6fe7a7a61fb3de66d7fa6873498f0aedc3b464  ways_meta_attic.bin.idx
0c4aa9fc50905200e1d9791b582b5d8c2141a4a3  ways_meta.bin.idx
0e2734ea4182db9d2975907265cebefcc6ee7c39  way_tags_global_attic.bin.idx
ee98c733abed5f062eef8379e3dd7d170e41ee18  way_tags_global.bin.idx
e017bcee9dbdb29a097618225d0719faf3044a9c  way_tags_local_attic.bin.idx
58cd33b6b7fa95b70d47ee4168c0db5dde00bb7f  way_tags_local.bin.idx
```

**Comment by KidA001** [comment] 2019-12-11 19:28
Looks like my checksum is off
```
bvogelgesang@osm-vm:~/mnt/osm-db$ sha1sum *.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  node_keys.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  nodes.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  nodes.map.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  node_tags_global.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  node_tags_local.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  relation_keys.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  relation_roles.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  relations.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  relations.map.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  relation_tags_global.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  relation_tags_local.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  way_keys.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  ways.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  ways.map.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  way_tags_global.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  way_tags_local.bin.idx
```

should I rm -rf my database files and re-download with the clone?

**Comment by KidA001** [comment] 2019-12-11 19:33
I'm starting a new download with `download_clone.sh`
it looks like I'm getting 2019-12-11 files, the replicate_id is `3797119` and the base_url is `https://dev.overpass-api.de/clone//2019-12-11`

**Comment by mmd-osm** [comment] 2019-12-11 19:34
I find it odd that the checksum identical for each file. Do you see the same result when checking a single file only?

I think you probably need to download those files again. You can also directly mirror files from dev.overpass-api.de/clone which is the endpoint used by the clone script.

**Comment by mmd-osm** [comment] 2019-12-11 19:38
Related issue: https://github.com/drolbr/Overpass-API/issues/493

**Comment by KidA001** [comment] 2019-12-11 19:42
Because it's such a large file size I can't store these files directly on my VM's disk. Google Cloud VM's only allow a max disk size of 65GB, therefore I'm mounting a Cloud Storage bucket to disk with [gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse) and storing them there. At a system level it treats this mounted disk as a regular file system, but it is very likely that CloudStorage might be messing with these files?

In any case I'm re-downloading and should have updated files in an hour or so and will follow up

**Comment by mmd-osm** [comment] 2019-12-11 19:50
It’s quite likely you’re the first person to try this setup w/ Overpass, and you may hit some previously unknown issues. Overpass prod instances run on a dedicated server, and doesn’t use any cloud services.

**Comment by KidA001** [comment] 2019-12-11 21:06
Hard to know what would be so different on a VM, but that might explain what's going on. Off the cuff, do you know what might cause `osm3_query` to return an empty result with no errors when you query it?

**Comment by mmd-osm** [comment] 2019-12-11 21:13
If the index file doesn’t match the corresponding data file, you might not find the value you’re looking for in the index, or the index might point to some incorrect location. All different forms of data inconsistencies.

**Comment by KidA001** [comment] 2019-12-11 21:43
@mmd-osm ok so I've re-downloaded all the files. When I run `osm3_query` and point it to the DB directory and run a query, I'm now getting `runtime error: open64: /home/bvogelgesang/mnt/osm-db/node_tags_global.bin.idx File_Blocks_Index: Unsupported index file format version`

Here are the checksum's I have
```
9a8c7efca7e5aefbcbb86a9ad6cffa0df3704bfc  node_keys.bin.idx
76f112f184f56e09887111c9a0a81fa6d9787074  nodes.bin.idx
088c27d83a0a852853b2215dea7102a4aec16598  nodes.map.idx
08abcbd907f610f8f46b089bff9a5a6e6a06eb06  node_tags_global.bin.idx
710cc80c5b94b1972ff1ffe2c1cea59e743b8f34  node_tags_local.bin.idx
77328bfbc493d1aa6e3e9eef3264aa85a944583f  relation_keys.bin.idx
3745d06d6da1c9836421ced24bef3f857b4f9f31  relation_roles.bin.idx
1af7a40376802d6c334bb5659e34f848ebaa9460  relations.bin.idx
cf3ed2797ed3a87cde1f300559c375ee8dbebb2d  relations.map.idx
56cd563e116b2bad5fad013eee0a936b442f8fe5  relation_tags_global.bin.idx
ae77a127b70d1bd339c6d8a8f34ffe4e4292a4bd  relation_tags_local.bin.idx
0e10f09331043971f2526d91fec0dceccd67a51b  way_keys.bin.idx
4d586de23c70fbab3732e8c57a8bd835a6fe0cf9  ways.bin.idx
64f4b82497ef4ec82f3211f3d663e03ca25793f2  ways.map.idx
e6e7dd1803425e695c0755009f000faeed3961eb  way_tags_global.bin.idx
0ea1e9f93b975a8ff4789eb71bc88ffd78ff7229  way_tags_local.bin.idx
```

Looking better than last time..

**Comment by mmd-osm** [comment] 2019-12-11 21:55
Ok, I collected the sha1sum for files dated 2019-12-11 now, replicate id is 3797119. I think they still differ from what I see in your list.

```
clone/2019-12-11$ sha1sum *.idx
62184b709d71efef178fb26a75fafa501489222a  node_attic_indexes.bin.idx
712fbdb72038243ef5deffb8afe6e0fa3dee099e  node_changelog.bin.idx
68212bacd578dabc8956aac564a44c28896d39f9  node_keys.bin.idx
7af2d7711be4b612674096a16cdea41d7c103d99  nodes_attic.bin.idx
12bd2cee5fc0b525f7addb675931b3bea6c572b6  nodes_attic.map.idx
2338a59e80e46cd0919000b7fb99637c60ad4528  nodes_attic_undeleted.bin.idx
7d539b13a7f0d3f096fc3af84904befb1b34d05e  nodes.bin.idx
c9c337783b11fa433f6aac8eec3e56553576cb7b  nodes.map.idx
251203e19105ea1eb58d631fd9e03a271c35fa90  nodes_meta_attic.bin.idx
9a9ddd0b0f3800935244784ab505463d6d1b7628  nodes_meta.bin.idx
6b2a27cc08b387fbdd12e10894ec6a7bd366e92b  node_tags_global_attic.bin.idx
14e0e3ee84ab23a04a14bdcde43699399a225bce  node_tags_global.bin.idx
3e5868d17a1e3bb4afe2b9f2d402dc6381971584  node_tags_local_attic.bin.idx
8a1662d1f9317bce695fbdde42bd276960a430d8  node_tags_local.bin.idx
56f7de8ecccaba2f51ca6a456468c9fb764abfab  relation_attic_indexes.bin.idx
d5dd2466a37ed8d7ebde9bda2c1d5705a586d6a9  relation_changelog.bin.idx
77328bfbc493d1aa6e3e9eef3264aa85a944583f  relation_keys.bin.idx
3745d06d6da1c9836421ced24bef3f857b4f9f31  relation_roles.bin.idx
a3febde9407ed9d9c7f4f5ffe56bac4fc0a78bdb  relations_attic.bin.idx
cf3ed2797ed3a87cde1f300559c375ee8dbebb2d  relations_attic.map.idx
49720900f46cc4f298b0aa683e5395bd11fc831e  relations_attic_undeleted.bin.idx
1af7a40376802d6c334bb5659e34f848ebaa9460  relations.bin.idx
cf3ed2797ed3a87cde1f300559c375ee8dbebb2d  relations.map.idx
3541d5bf1b3c7f1017b861198df4174701bd6a27  relations_meta_attic.bin.idx
f79975dcd2bcd955b64f80b88df2b618a47b41c1  relations_meta.bin.idx
34be337e2a374abafee509b703416e2012539c5a  relation_tags_global_attic.bin.idx
56cd563e116b2bad5fad013eee0a936b442f8fe5  relation_tags_global.bin.idx
521449411b344f33e78331f496ed708b7d8bb6fa  relation_tags_local_attic.bin.idx
ae77a127b70d1bd339c6d8a8f34ffe4e4292a4bd  relation_tags_local.bin.idx
ec144ee8c2f43998f85f8d902a833c820b0a5dfc  user_data.bin.idx
2700f2764e2f31f588e83e39779ceb1188c29222  user_indices.bin.idx
03573a52aa4c9d5a53a3c02acd4baafeb9550714  way_attic_indexes.bin.idx
12882de10bf4dceecbbc49232d56b564ea484b7d  way_changelog.bin.idx
0e10f09331043971f2526d91fec0dceccd67a51b  way_keys.bin.idx
40771b63923040ef53bc2e8dce1eb3929762a992  ways_attic.bin.idx
8e1d439bd5bc997290a56abb170bf0383b3e1e9b  ways_attic.map.idx
d61e8edf641a419e6e4093bee46bcdbe2163690a  ways_attic_undeleted.bin.idx
d92e69b4dbd0d3510093212a9fccd87a5a43f15d  ways.bin.idx
b934da2c84bfe83456010545072e026c215954f5  ways.map.idx
149fca96e10e264fefa83757d925fb8aa0c26388  ways_meta_attic.bin.idx
d78ef8452bea414445013cf04f19ffd91b076c8f  ways_meta.bin.idx
9f71425829c92bb367ced15964cb4f4a0d6e5b07  way_tags_global_attic.bin.idx
e6e7dd1803425e695c0755009f000faeed3961eb  way_tags_global.bin.idx
39facc75dbe7dc9aba83796883b15dfd0b0e8eb5  way_tags_local_attic.bin.idx
7256fdfa96cafd6bf4fb95d85b807fac3b4d4fd7  way_tags_local.bin.idx

```

**Comment by KidA001** [comment] 2019-12-11 21:59
Agh, this is driving me nuts. I ran the clone_download.sh script and didn't do anything else with those files. Any idea 1) what would change the checksum and 2) why the files unchanged wouldn't work?

When I lookup the unsupported file error I see a note in the wiki saying I might have the incorrect version: https://wiki.openstreetmap.org/wiki/Overpass_API/Wording#Messages_from_the_backend

Is that not relevant?

**Comment by mmd-osm** [comment] 2019-12-11 22:05
> 1) what would change the checksum

Not really sure about this one. Can you try curl - without saving anything to disk:

**sha1sum:**

curl http://dev.overpass-api.de/clone/2019-12-11/node_tags_global.bin.idx | sha1sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  877k  100  877k    0     0  2760k      0 --:--:-- --:--:-- --:--:-- 2760k
14e0e3ee84ab23a04a14bdcde43699399a225bce  -

**md5sum:**

 curl http://dev.overpass-api.de/clone/2019-12-11/node_tags_global.bin.idx | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  877k  100  877k    0     0  2813k      0 --:--:-- --:--:-- --:--:-- 2813k
62c9664f7fd06faf4cfa1f8fbf1cb174  -


>  the wiki saying I might have the incorrect version

There are some occasional version changes. In this case, the files you're cloning should actually match the 0.7.55 version you're using.

**Comment by KidA001** [comment] 2019-12-11 22:10
Looks like I get the same as you
```
bvogelgesang@osm-vm:~/mnt/osm-db$ curl http://dev.overpass-api.de/clone/2019-12-11/node_tags_global.bin.idx | sha1sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  877k  100  877k    0     0   645k      0  0:00:01  0:00:01 --:--:--  645k
14e0e3ee84ab23a04a14bdcde43699399a225bce  -
```

```
bvogelgesang@osm-vm:~/mnt/osm-db$ curl http://dev.overpass-api.de/clone/2019-12-11/node_tags_global.bin.idx | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  877k  100  877k    0     0   620k      0  0:00:01  0:00:01 --:--:--  620k
62c9664f7fd06faf4cfa1f8fbf1cb174  -
```

I'm using `0.7.55.7` should I try `0.7.55` instead?

**Comment by mmd-osm** [comment] 2019-12-11 22:23
I would try downloading the same file via wget to your storage, and then validate file contents again by running sha1sum. If there’s some difference in there you need to do some troubleshooting on how you’re using that storage.

**Comment by KidA001** [comment] 2019-12-11 23:17
>  try downloading the same file via wget
You mean the OSM package or the DB Files?

Would I have better luck using the planet file?

**Comment by mmd-osm** [comment] 2019-12-12 06:47
The idea was:
* go to  error:  /mnt/disks/osm-db-disk/osm-db/
* Run wget http://dev.overpass-api.de/clone/2019-12-11/node_tags_global.bin.idx
* again sha1sum on that file and compare results

**Comment by KidA001** [comment] 2019-12-12 17:54
@mmd-osm Ok, just tried that and after downloading the new file I get a different error
`runtime error: Query failed with the exception: Zlib_Inflate: -3` I can't find anything online about it with a quick search, does that ring any bells?

**Comment by mmd-osm** [comment] 2019-12-12 17:55
Again, please compare those sha1sum results first before trying anything with Overpass API.

**Comment by KidA001** [comment] 2019-12-12 18:02
Yes now I'm getting `14e0e3ee84ab23a04a14bdcde43699399a225bce` for the sha1sum which seems correct...

**Comment by mmd-osm** [comment] 2019-12-12 18:07
How about the other files? Did you download any new files today, would you need some new sha1sums to compare results?

> I think Zlib_Inflate: -3 had something to do with available disk space

-3 in this case means "Z_DATA_ERROR", i.e. corrupt files in your database directory.

**Comment by KidA001** [comment] 2019-12-12 18:10
Should I go through and just re-download the files with wget? Will I cause issues if I have mixed files from 11 or 12th of december?

**Comment by mmd-osm** [comment] 2019-12-12 18:13
I think it would be best to delete all of the old database files before trying a new download. Mixing files will only cause issues down the road.

If you want to prioritize the download, I'd say, you can download files containing "attic" in the filename at a later point in time.

**Comment by KidA001** [comment] 2019-12-12 18:15
68212bacd578dabc8956aac564a44c28896d39f9  node_keys.bin.idx
7d539b13a7f0d3f096fc3af84904befb1b34d05e  nodes.bin.idx
c9c337783b11fa433f6aac8eec3e56553576cb7b  nodes.map.idx
14e0e3ee84ab23a04a14bdcde43699399a225bce  node_tags_global.bin.idx
8a1662d1f9317bce695fbdde42bd276960a430d8  node_tags_local.bin.idx
77328bfbc493d1aa6e3e9eef3264aa85a944583f  relation_keys.bin.idx
3745d06d6da1c9836421ced24bef3f857b4f9f31  relation_roles.bin.idx
1af7a40376802d6c334bb5659e34f848ebaa9460  relations.bin.idx
cf3ed2797ed3a87cde1f300559c375ee8dbebb2d  relations.map.idx
56cd563e116b2bad5fad013eee0a936b442f8fe5  relation_tags_global.bin.idx
ae77a127b70d1bd339c6d8a8f34ffe4e4292a4bd  relation_tags_local.bin.idx
0e10f09331043971f2526d91fec0dceccd67a51b  way_keys.bin.idx
d92e69b4dbd0d3510093212a9fccd87a5a43f15d  ways.bin.idx
b934da2c84bfe83456010545072e026c215954f5  ways.map.idx
e6e7dd1803425e695c0755009f000faeed3961eb  way_tags_global.bin.idx
da39a3ee5e6b4b0d3255bfef95601890afd80709  way_tags_local.bin.idx

Ok, i re-ran WGET for all my `*.idx` files and than ran the sha1sum, looks like I get the correct result. Any thoughts why this would different from the donwload_clone script?

**Comment by KidA001** [comment] 2019-12-12 18:17
When using the API, still getting
```
runtime error: open64: /home/bvogelgesang/mnt/osm-db/node_tags_global.bin.idx File_Blocks_Index: bad pos in index file
bvogelgesang@osm-vm:~/mnt/osm-db$ sha1sum node_tags_global.bin.idx
14e0e3ee84ab23a04a14bdcde43699399a225bce  node_tags_global.bin.idx
```

Should I Just plan to replace the rest of the files this way?

**Comment by mmd-osm** [comment] 2019-12-12 18:19
Yes, please replace all of the files by deleting the old ones first and then re-download. 
Not sure if you deleted your database directory earlier on, before trying a new download_clone.sh?

**Comment by KidA001** [comment] 2019-12-12 18:26
Ok, running a script to re-download all those files. This is the list of files I have to download:
```
node_keys.bin
node_keys.bin.idx
nodes.bin
nodes.bin.idx
nodes.map
nodes.map.idx
node_tags_global.bin
node_tags_global.bin.idx
node_tags_local.bin
node_tags_local.bin.idx
relation_keys.bin
relation_keys.bin.idx
relation_roles.bin
relation_roles.bin.idx
relations.bin
relations.bin.idx
relations.map
relations.map.idx
relation_tags_global.bin
relation_tags_global.bin.idx
relation_tags_local.bin
relation_tags_local.bin.idx
replicate_id
way_keys.bin
way_keys.bin.idx
ways.bin
ways.bin.idx
ways.map
ways.map.idx
way_tags_global.bin
way_tags_global.bin.idx
way_tags_local.bin
way_tags_local.bin.idx
```

I did delete the DB directory before running the `download_clone.sh` script. Is there anything else that needs to be run after that script before starting `osm3_query` ?

**Comment by mmd-osm** [comment] 2019-12-12 18:31
> Is there anything else that needs to be run after that script before starting osm3_query ?

No, the download_clone script is really only issuing some wget requests and has a bit of additional error handling.

Your list doesn't include any metadata files (nodes_meta.bin*, ways_meta.bin*, relations_meta.bin*,  user_data.bin*,  user_indices.bin*). If you don't need user names, or changeset numbers, that's ok.

**Comment by KidA001** [comment] 2019-12-12 18:51
Yes, we don't need the metadata. Files are re-downloading, i'll update with checksums in a bit here. Thanks again for being attentive to this thread and helping out.

**Comment by KidA001** [comment] 2019-12-12 20:49
Finished downloading, looks like the checksums match now. I'm going to try running osm3_query
```
bvogelgesang@osm-vm:~/mnt/osm-db$ sha1sum *.idx
68212bacd578dabc8956aac564a44c28896d39f9  node_keys.bin.idx
7d539b13a7f0d3f096fc3af84904befb1b34d05e  nodes.bin.idx
c9c337783b11fa433f6aac8eec3e56553576cb7b  nodes.map.idx
14e0e3ee84ab23a04a14bdcde43699399a225bce  node_tags_global.bin.idx
8a1662d1f9317bce695fbdde42bd276960a430d8  node_tags_local.bin.idx
77328bfbc493d1aa6e3e9eef3264aa85a944583f  relation_keys.bin.idx
3745d06d6da1c9836421ced24bef3f857b4f9f31  relation_roles.bin.idx
1af7a40376802d6c334bb5659e34f848ebaa9460  relations.bin.idx
cf3ed2797ed3a87cde1f300559c375ee8dbebb2d  relations.map.idx
56cd563e116b2bad5fad013eee0a936b442f8fe5  relation_tags_global.bin.idx
ae77a127b70d1bd339c6d8a8f34ffe4e4292a4bd  relation_tags_local.bin.idx
0e10f09331043971f2526d91fec0dceccd67a51b  way_keys.bin.idx
d92e69b4dbd0d3510093212a9fccd87a5a43f15d  ways.bin.idx
b934da2c84bfe83456010545072e026c215954f5  ways.map.idx
e6e7dd1803425e695c0755009f000faeed3961eb  way_tags_global.bin.idx
7256fdfa96cafd6bf4fb95d85b807fac3b4d4fd7  way_tags_local.bin.idx
```

**Comment by KidA001** [comment] 2019-12-12 21:21
Still getting an error
```bash
runtime error: open64: /home/bvogelgesang/mnt/osm-db/node_tags_global.bin.idx ```
File_Blocks_Index: bad pos in index file
```
```bash
bvogelgesang@osm-vm:~/mnt/osm-db$ sha1sum node_tags_global.bin.idx
14e0e3ee84ab23a04a14bdcde43699399a225bce  node_tags_global.bin.idx
```

That's the correct shasum. Any thoughts? I'm at a loss

**Comment by mmd-osm** [comment] 2019-12-13 15:20
No idea, really. I tried the same database files you were downloading and don't get any error, I'm unable to reproduce your issue and don't really know what might be the issue. Do you have any other box to try this out, like your own laptop? 

Maybe @drolbr has some further ideas?

> Would any of this be solved by using the planet file instead?

So your idea is to set up your own database based on a planet file? Well, you could download a planet.osm.bz2 file (PBF is not supported without using some external tool to convert it to OSM XML) and import that. Be warned though that this will take a lot of time to process, likely in the range of several days rather than some hours.

**Comment by KidA001** [comment] 2019-12-13 21:04
@mmd-osm I live off-grid and my internet connection is quite limited so I haven't tried it locally. I'm going to be on a faster connection this weekend and will see if I can get them locally. @drolbr any help/insight/theories would be appreciated.

The planet file is an option, but one I'm trying to avoid for that reason.

**Comment by mmd-osm** [comment] 2019-12-13 21:27
Interesting enough, while browsing for your combination of GCS and GCSFuse, I came across this one here: https://www.mobileread.com/forums/showthread.php?t=312181

_After a bit of tinkering involving my calibre library being corrupted ~3 times, I decided that the smarter thing to do would be to attach an actual disk (they call them "persistent storage disks"),_

_"So if anyone's reading this in the future, attach a damn disk, don't use GCS right now. "_

**Comment by KidA001** [comment] 2019-12-13 22:19
Wow, one thank you for poking around and searching on my behalf, greatly appreciated. Two, I'm going to delete GCSFuse with the rath of 1000 suns. I just created a persistent disk and am attaching it to my VM. I'll start a fresh download process and keep my fingers crossed. I'll follow up, thoughts and prayers.

p.s. if I get this working, I'm happy to create and share an image of a API on a working VM for anyone who wants to host it on GCloud or AWS.

**Comment by KidA001** [comment] 2019-12-14 05:48
Following up with some great news, it works. Corruption from GCSFuse/Cloud Storage seems to have been the culprit. I can now successfully query OSM. Thank you so much for taking the time to troubleshoot this with me.

We use OSM to help generate tactile maps for the visually impaired, it's been an incredibly useful tool. We'll be glad to have a local running copy of the DB to query. If it's at all useful I'm glad to follow up and post a template repo for launching a hosted OSM API on google cloud.

Many thanks

**Comment by KidA001** [comment] 2019-12-16 18:48
I'm running `nohup $EXEC_DIR/bin/dispatcher --osm-base --db-dir=$DB_DIR &` to start the dispatcher and an receiving a segment fault error
`[1]+  Segmentation fault      (core dumped) nohup $EXEC_DIR/bin/dispatcher --osm-base --db-dir=$DB_DIR`

I've found a few issues referencing this, but they have to do with users who have been download and installing diffs which I am not. Any thoughts on the cause of this?

**Comment by mmd-osm** [comment] 2019-12-17 17:31
I'm seeing you've already posted this one to the mailing list: https://listes.openstreetmap.fr/wws/arc/overpass/2019-12/msg00003.html

Can you please close this issue then? Thanks!

**Comment by KidA001** [comment] 2019-12-17 20:55
No response from anyone on the thread. Glad to close the issue but I have spent over a week trying to get this setup for a client and it might be time to move on. I even tried using the supplied docker image to no avail

**Comment by mmd-osm** [comment] 2019-12-17 20:57
Well, in any case it’s a new and unrelated issue and you should open a new github  issue for it.

**Comment by mmd-osm** [comment] 2019-12-17 21:00
Roland replied just 20 minutes ago: https://listes.openstreetmap.fr/wws/arc/overpass/2019-12/msg00007.html

**Closed** 2019-12-18 19:47 UTC
