### ISSUE TITLE
Augmented Diffs: Inclusion of changeset tags

### ISSUE THREAD

**Issue by ltog** [drolbr/Overpass-API#361] opened 2017-01-11 20:17 UTC
I have a use case where it would be beneficial to have augmented diffs include changeset tags (primarily the tags `source=` and `comment=`). Is there any chance they might be included in a future version?

If not, what would be an alternative to get changeset tags in real-time? I noticed that [Show Me The Way](https://osmlab.github.io/show-me-the-way/) calls https://www.openstreetmap.org/api/0.6/changeset/45085810 but assume that is frowned upon...

**Comment by mmd-osm** [comment] 2017-01-11 20:22
This looks like a duplicate of #189

**Comment by ltog** [comment] 2017-01-11 21:59
@mmd-osm : I'm not sure if it's an exact duplicate. As far as I could understand #189 the author is looking for a complete search functionality in changesets whereas I'm only looking to get them by ID.

Concerning getting the changesets in another fashion than with the Overpass API: I read https://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets and noticed that multiple changesets can be queried at once: https://www.openstreetmap.org/api/0.6/changesets?changesets=45085809,45085811,45085813

**Comment by mmd-osm** [comment] 2017-01-11 22:04
The issue here is that we don't have changeset metadata/tags available at
all as they're not included in the minutely diffs. Also see this comment:
https://github.com/tyrasd/overpass-turbo/issues/278#issuecomment-269317963

Regarding the main osm call you probably better ask tomH or zerebubuth.

**Closed** 2018-07-18 05:30 UTC
Labels: invalid
