### ISSUE TITLE
Exporting a request to Overpass QL cuts off "geom" from "out geom;"

### ISSUE THREAD

**Issue by naomap** [drolbr/Overpass-API#450] opened 2017-11-20 22:30 UTC
[ Was issue #349 in tyrasd/overpass-turbo ]
Given a request that uses the statement "out geom;", for instance :

rel[route=bus][network="Transpole"][ref=18];
way(r);
out geom;

Exporting that query to Overpass QL (compact or normal) cuts off 'geom' from the out statement, for no apparent reason. This makes it harder to reuse the request in uMap for instance...

**Comment by mmd-osm** [comment] 2017-11-20 23:16
This looks like a regression in statement dump...

**Comment by drolbr** [comment] 2018-04-11 14:39
Fixed in 6e2777bc4b8e29ac737e44d315150e2e76c184f6

**Closed by drolbr** 2018-04-11 14:39 UTC
Labels: bug
