### ISSUE TITLE
Attic data  Output action type="create" for modified object  ie. version > 1

### ISSUE THREAD

**Issue by pierzen** [drolbr/Overpass-API#292] opened 2016-07-07 13:53 UTC
The same attic query with small and large bbox returns different results.  See below Result for way id="412947345" version=3

**First query small bbox http://overpass-turbo.eu/s/hbr**
**&lt;action type="modify"&gt;**
&lt;old&gt;
  &lt;way id="412947345" version="1" timestamp="2016-04-23T12:10:08Z" changeset="38811990" uid="2246826" user="vichada"&gt;
  ...
  &lt;/way&gt;
&lt;/old&gt;
&lt;new&gt;
  &lt;way id="412947345" version="3" timestamp="2016-06-02T19:04:52Z" changeset="39761915" uid="77114" user="LLAQWA"&gt;

**Second query large bbox http://overpass-turbo.eu/s/haS**
**&lt;action type="create"&gt;**
&lt;way id="266147481" version="3" timestamp="2016-06-02T19:04:51Z" changeset="39761915" uid="77114" user="LLAQWA"&gt;

**Comment by mmd-osm** [comment] 2016-07-07 14:07
I think that's a duplicate of https://github.com/drolbr/Overpass-API/issues/244

**Comment by pierzen** [comment] 2016-07-07 14:26
thanks @mmd-osm  for your explanations in #244. I did not see the previous issue, and yes this is the same subject. Will continue the discussion in #244.

**Comment by mmd-osm** [comment] 2016-07-07 14:38
Ah,sorry. Maybe, I'm mistaken,in your first example you mentionen way 412947345, in example 2 however, it's way 266147481. I guess that's not as expected?

**Comment by pierzen** [comment] 2016-07-07 15:07
Sorry, a Cut and paste error making an example with way in both files. Example should be for way 412947345 which is in both outputs.

**First query small bbox http://overpass-turbo.eu/s/hbr**
**&lt;action type="modify"&gt;**
&lt;old&gt;
  &lt;way id="412947345" version="1" timestamp="2016-04-23T12:10:08Z" changeset="38811990" uid="2246826" user="vichada"&gt;
    &lt;tag k="building" v="yes"/&gt;
  &lt;/way&gt;
&lt;/old&gt;
&lt;new&gt;
  &lt;way id="412947345" version="3" timestamp="2016-06-02T19:04:52Z" changeset="39761915" uid="77114" user="LLAQWA"&gt;
    &lt;tag k="building" v="yes"/&gt;
    **&lt;tag k="damage:event" v="2016EcuadorEarthquake"/&gt;**


**Second query large bbox http://overpass-turbo.eu/s/haS**
**&lt;action type="create"&gt;**
  &lt;way id="412947345" version="3" timestamp="2016-06-02T19:04:52Z" changeset="39761915" uid="77114" user="LLAQWA"&gt;
    &lt;tag k="building" v="yes"/&gt;
    **&lt;tag k="damage:event" v="2016EcuadorEarthquake"/&gt;**

**Closed** 2016-07-07 15:42 UTC
