### ISSUE TITLE
OSM XML output contains elements in wrong order

### ISSUE THREAD

**Issue by matthijsmelissen** [drolbr/Overpass-API#460] opened 2018-02-04 02:27 UTC
The [https://wiki.openstreetmap.org/wiki/OSM_XML#Contents](wiki) states that OSM XML files contain blocks of nodes, ways and relations. They should be in this order.

However, Overpass API sometimes outputs ways before nodes. Example:

https://overpass-api.de/api/interpreter?data=%28%0D%0A%20%20way%5B%22highway%22%3D%22motorway%22%5D%2851.1%2C4.1%2C51.2%2C4.2%29%3B%0D%0A%29%3B%0D%0Aout%20meta%3B%0D%0A%3E%3B%0D%0Aout%20meta%20qt%3B%20

**Comment by mmd-osm** [comment] 2018-02-04 07:35
Duplicate of #265.

**Closed** 2018-02-23 06:52 UTC
Labels: duplicate
