### ISSUE TITLE
block of nodes is supposed to appear before block of ways

### ISSUE THREAD

**Issue by matkoniecz** [drolbr/Overpass-API#265] opened 2016-04-09 16:51 UTC
http://overpass-api.de/output_formats.html has 

> The XML data itself, i.e. the tags node, way and relation are returned exactly as from the main server.

linking to http://wiki.openstreetmap.org/wiki/OSM_XML which includes

> a block of nodes containing especially the location in the WGS84 reference system (...) a block of ways

and

> If you develop tools using this format, you can be certain that:
> 
>    blocks come in this order

```
[out:xml][timeout:25];
(
  way["building"](37.95536,126.67604,37.95672,126.67774);
);
out body;
>;
out skel qt;
```

running on http://overpass-api.de/query_form.html returns https://gist.github.com/matkoniecz/f1f8d9b4d31cca7d383f8e36b8da0a65 that has block of ways before block of ways. It breaks for example import to https://github.com/OpenOrienteering/mapper

**Comment by mmd-osm** [comment] 2016-04-09 16:55
Why don't you output the nodes first?

```C
way["building"](37.95536,126.67604,37.95672,126.67774)->.a;
node(w.a);
out meta;
.a out meta;
```

**Comment by matkoniecz** [comment] 2016-04-09 17:37
@mmd-osm Thanks for the workaround!

**Comment by mmd-osm** [comment] 2016-04-09 17:41
Great. If the issue is resolved, I kindly ask you to close this issue. Thanks!

**Comment by matkoniecz** [comment] 2016-04-09 19:41
I think that it is not resolved.

Either "The XML data itself, i.e. the tags node, way and relation are returned exactly as from the main server." should be amended to mention that there are differences (or at least this difference) and produced file is not a valid osm file. 

The (I think preferable) solution would be to ensure that nodes are returned first by default, without specially requesting this.

**Comment by matkoniecz** [comment] 2016-04-09 19:43
The third possibility is that http://wiki.openstreetmap.org/wiki/OSM_XML is wrong and "blocks come in this order" is not required for .osm file to be valid and consumers of .osm data should be expected to handle this.

**Comment by mmd-osm** [comment] 2016-04-09 19:51
The main question is, where did you get your original query from?

If it has been created via overpass turbo (which I believe it does based on the typical `out body; >; out skel qt;`sequence), then overpass turbo also defines the order in which elements appear. If you think this is not ok, you should raise an issue with overpass turbo instead: https://github.com/tyrasd/overpass-turbo. This is nothing Overpass API can change. The query was just created so that ways are returned first, followed by the way's nodes.

If you created the query own your own, you're in control and define the output in whatever sequence you like.

The query I provided is really not a "workaround", it is just one way of returning data from Overpass API and you have all the options to do what works best for you.

**Comment by matkoniecz** [comment] 2016-04-10 03:01
As I understand, "you're in control and define the output in whatever sequence you like" means that one may design query in such way that `[out:xml]` gives valid osm file (nodes before ways before relations), but it is also possible to generate invalid osm file (for example ways before nodes).

The question is whatever it is desirable - is it just because generally it is not a problem/it is easier to code/to maintain the same order as on json mode/etc. In any case http://overpass-api.de/output_formats.html should be amended to explain that one may design query to output valid .osm file, but it is also possible to generate an invalid one (what may be for some reason desirable).

Or maybe overpass should in `[out:xml]` mode always generate valid .osm file, with block of nodes first - no matter order demanded by query. It would be probably more complex to do and in turn cause problem for somebody else relying on undocumented behaviour.

**Comment by mmd-osm** [comment] 2016-04-10 09:01
As long as you only have a single `out;` statement in your query, you will get the standard OSM XML sequence node, way and relation.

With multiple `out;` statements (or with a `foreach` loop), sorting results across several `out` statements is both changing semantics (as one example, see https://github.com/drolbr/Overpass-API/issues/236) and technically not desirable.

**Comment by mmd-osm** [comment] 2017-03-04 15:41
@matkoniecz : as mentioned in https://github.com/tyrasd/overpass-turbo/issues/230 and in my previous comments, there's nothing which would inhibit you from specifying a query to produce correct OSM XML. On the other hand it's your responsibility to do it the right way. If your query outputs data in some different sequence, you will get the data in exactly that sequence.

This *works exactly as designed*. Therefore, I'd kindly request you to close this issue.

**Closed** 2017-05-25 10:27 UTC
Labels: question
