### ISSUE TITLE
Potential regex bug

### ISSUE THREAD

**Issue by SwiftFast** [drolbr/Overpass-API#405] opened 2017-06-09 10:10 UTC
I would like to obtain all nodes in a region that have no `name` tag but do have `name:lang`. The following query returns nodes that do have a name tag, even though it shouldn't:

```
node[!"name"][~"^name:(.*)$"~".*"];
```

**Comment by mmd-osm** [comment] 2017-06-09 10:11
This is most likely a duplicate of https://github.com/drolbr/Overpass-API/issues/192

Please follow up in said issue.

**Comment by SwiftFast** [comment] 2017-06-09 10:15
Done.

**Closed** 2017-06-09 10:14 UTC
