### ISSUE TITLE
apply_osc_to_db.sh Zlib_inflate::Error

### ISSUE THREAD

**Issue by PocketPro** [drolbr/Overpass-API#302] opened 2016-07-26 01:29 UTC
Hello, 

I've installed overpass api on an ubuntu machine and I'm having troubles applying daily diffs. Up until a few days ago I was able to pull and apply daily diffs but today I started the machine, started the dispatcher daemon, fetched the latest diffs (three or four days worth), and apply_osc_to_db.sh results in the following error:

> terminate called after throwing an instance of 'Zlib_Inflate::Error'
>   what():  Zlib_Inflate: -5
> /home/ubuntu/osm3s/exec/bin/apply_osc_to_db.sh: line 115:  1696 Aborted                 (core dumped) ./update_from_dir --osc-dir=$1 --version=$DATA_VERSION $META --flush-size=0
> File_Error 17 File exists /home/ubuntu/osm3s/db/osm_base_shadow.lock write_start:1

Is this something you have seen before? Perhaps a result of turning off the machine before a process terminated? Fiddling I can restart the process by deleting the ism_base_shadow.lock file but applying the changes fails in the same manner?

Thoughts?

**Comment by mmd-osm** [comment] 2016-07-26 07:18
That's a known issue, see https://github.com/drolbr/Overpass-API/issues/295 and https://github.com/drolbr/Overpass-API/issues/298#issuecomment-234059697

**Comment by drolbr** [comment] 2016-07-27 04:09
No, this has nothing to do with #295 or #298.

It's the zlib library returing the error Z_BUF_ERROR. I'll have a look what might cause that error.

**Comment by mmd-osm** [comment] 2016-07-27 04:46
Well, my answer was a bit short. I assumed there was a previous crash
caused by #295 and the db is now corrupted. When applying further updates
to such a db, such zlib errors also occurred before during my tests.

Am Mittwoch, 27. Juli 2016 schrieb Roland Olbricht :

**Comment by drolbr** [comment] 2016-07-27 04:53
To the restart issue: It cannot get worse. Hence, I would give it a try.

What is happening is that Zlib claims to have found more data than it could decompress. It could be a disk error, but it is very unlikely that this results in a valid checksum.

More likely, this is a rarely happening bug in the software. If the update fails again, I'll supply a test program to catch that bug.

**Comment by mmd-osm** [comment] 2016-07-27 16:19
Ok, I see your point., The output shows return code -5, but is that the real return code we get back from inflate?

```C
  int ret = inflate(&strm, Z_FINISH);

  if (ret == Z_STREAM_ERROR || ret == Z_NEED_DICT || ret == Z_DATA_ERROR || ret == Z_MEM_ERROR)
    throw Error(ret);
  if (ret != Z_STREAM_END)
    throw Error(Z_BUF_ERROR); // Decompression incomplete
```

Wouldn't that imply that Z_OK, Z_ERRNO, Z_BUF_ERROR and Z_VERSION_ERROR are all reported back as Z_BUF_ERROR?

```C
#define Z_OK            0
#define Z_ERRNO        (-1)
#define Z_BUF_ERROR    (-5)
#define Z_VERSION_ERROR (-6)
```

**Comment by mmd-osm** [comment] 2016-12-11 16:24
@PocketPro : are there any new insights from your side in the meantime? Did the issue reoccur after starting from scratch? Were you able to reproduce it and can provide further details maybe?

If the issue did not reoccur, I'd kindly ask to you close this issue. Thanks.

**Comment by drolbr** [comment] 2017-03-02 16:40
No further feedback since three month. Hence I close the issue now.

**Closed by drolbr** 2017-03-02 16:40 UTC
Labels: bug
