### ISSUE TITLE
Attic data - Query id all or specific object version update

### ISSUE THREAD

**Issue by pierzen** [drolbr/Overpass-API#282] opened 2016-06-04 17:22 UTC
While the Attic database contains all versions of an object, there are no Overpass queries similar to the OSM API 0.6 to extract specific or all versions of an object.  Adding this possibility in Overpass would offer more flexibility with Overpass Attic queries and reduce queries to the OSM API.
### Unefficient way to do it actually

From Overpass, we can presently repetitively query reducing successively the Datetime statement with a time earlier then the last output obtained from an Attic database. But this is not an efficient query and consumes more server ressources.
_Example for node 22219529_ 

```
version="17" timestamp="2016-04-13T18:57:27Z"
version="16" timestamp="2016-04-13T17:14:28Z"
version="15" timestamp="2016-04-13T09:27:05Z"
```

we can get version 16 by reducing the datetime by one second

```
[date:"2016-04-13T18:57:26Z"];
node(22219529);
then  version 15
[date:"2016-04-13T17:14:27Z"];
node(22219529); 
```
### Enhancement proposition

Adding Functionalities similar to the osm api 0.6 would provide more flexibility.

```
http://www.openstreetmap.org/api/0.6/node/22219529/history  - all versions
http://www.openstreetmap.org/api/0.6/node/22219529/16       - version 16
```

Queries could be formulated adding suffix or [@version] parameter to the id
example
Query for version=2

```
node(id:2)
or
node(id)["@version"="2"]
```

Query of all all versions of the object

```
node(id:'history') 
or
node(id)["@version"="."]
```

**Comment by mmd-osm** [comment] 2016-06-04 17:27
Looks a bit like a duplicate of https://github.com/drolbr/Overpass-API/issues/219. 

@mvexel : is this in line to what you originally planned for #219. Can we merge both issues into a single one, e.g. by closing #219 and continue here?

**Comment by pierzen** [comment] 2016-06-04 21:32
@mmd-osm  yes this is similar to #219 

The OSM API limits the number of extractions. This is not a feasible solution to extract high volume of data.

https://github.com/pierzen/osm-contributor-stats builds contributor statistics for an area. It builds various contribution statistics by changesets.  The data is extracted from the OSM API but the amount that can be extracted is limited and do not let analyse large regions. As an example, it was possible with OSMContributorStats to analyze the contributions for the Nepal activation in 2014, to show the daily contribution and the long tail of the OSM contributions. There were 7,000 contributors but 500 of them contributed to 75% of objects edited. (http://fr.slideshare.net/pierzen/kll-workshop-2015-0809-openstreetmap-response-2015-nepal-earthquake)

I want to go further in the analysis and identify problematic contributions that need corrections. We need to focus on the thousand of contributors that start and often stop rapidly to contribute. We cannot control the various organizations that collaborate, but we can monitor the contributors and the data added to the map.  We need a different perspective on the data added to the map then simply revising a square through the Tasking Manager or to look at individual objects through the various Data Quality tools.

Analysis of dynamic data can help and Overpass offers the possibility to obtain rapidly such data. I can easily extract data for large regions with the Overpass Adiff queries. But I need to complete with the missing versions of objects since Overpass returns only the first and last versions.

**Comment by drolbr** [comment] 2017-05-26 03:35
For the record: https://github.com/openstreetmap/openstreetmap-website/issues/1067 is about reverting changesets. I.e. it should be easy to get all changed data as it were immediately before a changeset.

**Comment by drolbr** [comment] 2017-07-15 07:20
Implemented with two new features: [timeline](https://github.com/drolbr/Overpass-API/blob/new_features/src/overpass_api/statements/timeline.h#L30) and [retro](https://github.com/drolbr/Overpass-API/blob/new_features/src/overpass_api/statements/retro.h#L30), currently in the new_features branch.

You can get a list of all visible versions of a feature as follows:
```
timeline(node,1);
foreach(
  retro(u(t[created]))
  (
    node(1);
    out meta;
  );
);
```
If you want in addition information about deleted versions then you could display the timeline objects:
```
timeline(node,1);
foreach(
  out;
  retro(u(t[created]))
  (
    node(1);
    out meta;
  );
);
```
It works similar for ways and relations.

For ways and relations, you can in addition get extra information by using other output modes or more complex queries in the retro block:
```
timeline(way,268533452);
foreach(
  retro(u(t[created]))
  (
    way(268533452);
    out geom;
  );
);
```
Or get the members of relations:
```
timeline(rel,2706);
foreach(
  retro(u(t[created]))
  (
    ( rel(2706); >; );
    out meta;
  );
);
```

**Closed by drolbr** 2017-07-15 07:20 UTC
Labels: enhancement

**Comment by matkoniecz** [comment] 2017-12-16 11:01
Do you know when this feature will become deployed on any server accessible to general public? Is there maybe some test server with this version deployed?

**Comment by mmd-osm** [comment] 2017-12-16 11:06
> Is there maybe some test server with this version deployed?

Sure, you can use `//dev.overpass-api.de/api_mmd/ ` for testing.

**Comment by matkoniecz** [comment] 2017-12-16 11:11
What is the recommended usage limit? I assume that it is far lower than 

> You can safely assume that you don't disturb other users when you do less than 10.000 queries per day and download less than 5 GB data per day

for normal servers. Also, would it be a good idea to list this server at server list in https://wiki.openstreetmap.org/wiki/Overpass_API#Introduction ?

**Comment by mmd-osm** [comment] 2017-12-16 11:15
As that's our **development** server, there's absolutely zero guarantee for availability, which makes it unsuitable to be listed on the wiki page. You can test the feature there and report back some issues you encounter. Productive usage for any purpose is discouraged for obvious reasons.

**Comment by matkoniecz** [comment] 2017-12-16 12:27
> You're very welcomed to test the feature, though and report back any issues you encounter. The server runs on hard disk, so response times may be slow at times.

That is why I was asking about quota - I am not sure how strongly I such limit test queries (is it to much to do 50? 500? 1000?).

**Comment by mmd-osm** [comment] 2017-12-16 14:01
Good question. I don’t think we have a defined quota. At this time my proposal would be we‘ll let you know if it’s too much.

**Comment by mmd-osm** [comment] 2018-02-16 22:53
```
timeline(way,561040198);
foreach(
  retro(u(t["created"]))
  (
    way(561040198);
    out meta geom;
  );
);
```

Returns:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.58_mmd ">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2018-02-16T22:50:01Z"/>

  <way id="561040198" version="1" timestamp="2018-02-13T16:09:49Z" changeset="56327450" uid="5631066" user="osm_fede">
    <bounds minlat="45.5267951" minlon="10.5512585" maxlat="45.5268377" maxlon="10.5513489"/>
    <nd ref="2006812879" lat="45.5267951" lon="10.5513489"/>
    <nd ref="5410169836" lat="45.5268377" lon="10.5512585"/>
    <tag k="highway" v="steps"/>
  </way>
  <way id="561040198" version="2" timestamp="2018-02-13T20:53:24Z" changeset="56334244" uid="73405" user="ciclista">
    <bounds minlat="45.5267951" minlon="10.5512585" maxlat="45.5268377" maxlon="10.5513489"/>
    <nd ref="2006812879" lat="45.5267951" lon="10.5513489"/>
    <nd ref="5410169836" lat="45.5268377" lon="10.5512585"/>
  </way>
  <way id="561040198" version="3" timestamp="2018-02-14T07:06:55Z" changeset="56344326" uid="73405" user="ciclista">
    <bounds minlat="45.5267951" minlon="10.5512585" maxlat="45.5268377" maxlon="10.5513489"/>
    <nd ref="2006812879" lat="45.5267951" lon="10.5513489"/>
    <nd ref="5410169836" lat="45.5268377" lon="10.5512585"/>
    <tag k="highway" v="steps"/>
  </way>

</osm>
```

Version 2 is invisible, and should not be shown in the result output.
