### ISSUE TITLE
Some areas show a large amount of repeated tags

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#699] opened 2023-08-07 19:34 UTC
In particular for large areas, I've noticed that the query examples below return a fairly large amount of identical k=v pairs. I'm not exactly clear when this started to happen. At least one kumi.systems instance running on Overpass API 0.7.59 e21c39fe already showed the bug.

Example 1:

```c++
is_in(41.1100114129846,-98.86948585510254);
out;
```

Example 2:

```c++
area(3600148838);
out;
```

Result:

```xml
  <area id="3600148838">
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
    <tag k="ISO3166-1" v="US"/>
[...]
```

On overpass-api.de, the query returns about 130'000 tags, on kumi.systems, even more than 700'000 tags for one area.
Expected result would be around 350 tags.

**Comment by drolbr** [comment] 2023-08-08 03:30
I can confirm the issue.

**Comment by drolbr** [comment] 2023-08-10 04:53
Fixed in 4133829eb7c03619b82e09df846855450b2207eb

**Closed by drolbr** 2023-08-10 04:53 UTC
Labels: bug

**Comment by mmd-osm** [comment] 2023-08-10 13:21
Thank you for the fix.  I would assume that the incorrect area entries will fix themselves after some time.
Nevertheless, would you recommend some manual cleanup activity in this case, like re-creating areas from scratch?

**Comment by drolbr** [comment] 2023-08-10 15:13
I have re-created the areas on gall and lambert because not all tags get
fixed otherwise. Also, recreating areas from scratch there was 40
minutes or so, so not really a long downtime to get past this bug.
