### ISSUE TITLE
DB update scripts and dispatcher failure

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#430] opened 2017-09-05 07:16 UTC
As reported by @breki on the mailing list:

Hi,

I notice that if the main dispatcher stops working for some reason (file locks etc.), the apply_osc_to_db.sh script does not really detect that, instead its log reports new diffs were applied in a rapid fashion without reporting any errors (cca. 1 second for a diff, while it usually takes around 15 seconds). 

After that, the DB gets inconsistent (missing nodes, ways etc.) and it's basically useless and needs to be recloned.

**Comment by mmd-osm** [comment] 2017-09-06 15:29
Basic details: I run both the main dispatcher and the diff script (as described on my page) as systemd units. Since I don't keep the server running when I don't need Overpass, I pm-suspend it until the next use. Usually, after I bring the machine back from suspension:

    the main unit (dispatcher) is down for some reason (I don't really know why, but I do know I have to delete the lock files before I can restart it), 
    while the diff unit goes on applying next diffs and does not detect the main service being down, as I described in the initial mail.


    If the logfile of the dispatcher ($DB_DIR/transactions.log) is of a decent size then please send that file. 


Unfortunately I don't have it any more, I cleaned everything and recloned the database since I needed a working instance. I have restarted the diff service and when it happens again, I'll send the files.
 


    Has the script, in particular update_from_dir called from the script, produced any output? If so, could you please send that as well?


I'm running the script as a systemd unit. I can't find any output other than apply_osc_to_db.log and transaction.log files, unless it saves the output somewhere else?
 


    Could you please verify which script is actually running? Your documentation
    https://wiki.openstreetmap.org/wiki/User:Breki/Overpass_API_Installation#Configuring_Diffs
    mentions both apply_osc_to_db.sh and fetch_osc_and_apply.sh

No, only one script (.sh) is mentioned. It runs fetch_osc_and_apply.sh and the script writes into apply_osc_to_db.log file.

**Comment by mmd-osm** [comment] 2017-09-06 15:30
I tried to simulate this via vagrant suspend + up and found that
osm3s_query immediately returned with:

runtime error: open64: 32 Broken pipe /osm3s_v0.7.54_osm_base
Dispatcher_Client::request_read_and_idx::socket::1

... while dispatcher crashed with a SIGBUS error right after it received
a command from osm3s_query.

Not sure if this is the same in your setup.

For further analysis, I would turn off diff processing before triggering
the pm-suspend, then after resume:

- find out the dispatcher process id

  $ pidof dispatcher
  -> returns #process_id, e.g. 1234

- attach gdb to the running dispatcher process,

  $ gdb
  attach #process_id     e.g.: attach 1234
  continue

- run some query via osm3s_query and

- see where the dispatcher crashes.

**Comment by breki** [comment] 2017-09-06 17:46
The thing is, I can't reproduce this behavior on each suspend. I've suspended the machine twice now and Overpass is running without problems (it returns results via query web form and `osm3s_query` reports the base file is present so it doesn't want to execute the query).

**Comment by mmd-osm** [comment] 2017-09-07 09:26
I could also only reproduce a dispatcher crash sometimes. Most reliable so far:
1. Start dispatcher 
2. suspend 
3. resume
4. run first query via osm3s_query.

If I do step 4 before step 2, all is good.

**Comment by drolbr** [comment] 2017-09-09 10:12
Part of the problems addressed in fd856219cf3fe19b0cfe3864f3ce9f2a19f25054.

**Comment by drolbr** [comment] 2018-02-23 06:40
Classified as invalid. If I call the communications right from the mailing list, it looks like a bug in systemd.

**Closed** 2018-02-23 06:44 UTC
Labels: invalid
