### ISSUE TITLE
Case (in)sensitivity on key regexes

### ISSUE THREAD

**Issue by tyrasd** [drolbr/Overpass-API#182] opened 2015-01-18 17:58 UTC
(moved from https://github.com/tyrasd/overpass-turbo/issues/141, by @SpocWeb):

* Key regexes cannot be made case insensitive in a QL query (throws syntax error).
* Sometimes, when a key regex is combined with a case insensitive value regex, no results are found (while it returns data in case sensitive mode): [example](http://overpass-turbo.eu/s/76O). (applies to both QL and XML queries)
* It is not obvious to which regex a `case="ignore"` refers to in a XML query.

**Comment by mmd-osm** [comment] 2015-01-18 18:39
Regarding the 2nd point: it seems that parameter `,i` will turn the query into an exact key and case-insensitive regex value match.

Your second example will fail, as there's no key with exact match `[A-Z]` available. So, the additional `~` for regex keys doesn't have an effect yet, once `,i` is present.


[Source link 1](https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/frontend/map_ql_parser.cc#L1178), [Source link 2](https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/frontend/map_ql_parser.cc#L1196), [Source link 3](https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/frontend/map_ql_parser.cc#L423).

**Comment by drolbr** [comment] 2015-01-18 19:45
Thank you for producing the example. This is a real and now reproducible bug.

**Comment by mmd-osm** [comment] 2015-01-19 21:58
I've created a fix in #185 to have QL on par with Overpass XML again. The above [test query](http://overpass-turbo.eu/s/76O) now returns 3 ways again on my local test instance (31572091 + 666 + 31572091).

Regarding the other points: `case="ignore"` as well as `,i` will affect both key and value matches (=all or nothing principle).

**Comment by mmd-osm** [comment] 2015-03-08 08:17
Fix is now available for testing: http://overpass-turbo.eu/s/84y

Please take a look if everything works as expected.

**Comment by vincentdephily** [comment] 2015-06-17 08:52
The fix works for me. I was hit by the bug in http://overpass-turbo.eu/s/9YD . Any idea of when this'll be upstreamed ?

**Comment by mmd-osm** [comment] 2015-06-23 13:38
Sorry, I have no idea when this will get merged. You need to ask Roland // ping @drolbr

**Closed** 2016-08-03 09:57 UTC
Labels: bug

**Comment by drolbr** [comment] 2016-08-03 09:58
Fixed in cb8cb551d265d9fa0c1f1f6a219d54d320c559be after merge of https://github.com/drolbr/Overpass-API/pull/185 .

**Comment by zstadler** [comment] 2016-08-16 07:55
Please consider updating the [reference to this issue](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Case_insensitively_2) in the Overpass QL wiki page.

**Comment by vincentdephily** [comment] 2016-08-17 13:46
Better wait until the fix is deployed before updating the wiki ? At least on http://overpass-turbo.eu/ it's not yet the case.

**Comment by freayd** [comment] 2016-10-23 21:55
Seems like the fix is now running live. Anyone can confirm? If so the wiki should be updated as suggested by zstadler.

**Comment by vincentdephily** [comment] 2016-10-24 08:59
Looks live to me too. [wiki](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Case_insensitively) updated. Thanks.

**Comment by mmd-osm** [comment] 2016-10-24 17:35
Main & French instance already have the fix, rambler should follow very soon.
