### ISSUE TITLE
delivering broken data

### ISSUE THREAD

**Issue by malenki** [drolbr/Overpass-API#210] opened 2015-05-03 16:58 UTC
When downloading [this area](https://www.openstreetmap.org/#map=19/28.02680/85.11193) via Overpass API [​way number 340431930](https://www.openstreetmap.org/way/340431930) isn't displayed in JOSM, though one can select and edit it. 
After downloading the area from OSM via download area or download object it is displayed normally.

In JOSM's bugtracker [the bug got closed as [othersoftware] ](https://josm.openstreetmap.de/ticket/11401#comment:1) (image and exampla data there, too) since the downloaded data is missing a node. Thus I assume I should file the bug against the API…

**Comment by mmd-osm** [comment] 2015-05-03 17:49
Minimum test case: `way(340431930);out geom;`

Way 340431930 refers to some nodes, which are no longer available like: `node(3488830107);out meta;`

Result:

```XML
  <way id="340431930">
    <bounds minlat="28.0257255" minlon="85.1107004" maxlat="28.0399973" maxlon="85.1200248"/>
    <nd ref="3490601202" lat="28.0399973" lon="85.1200248"/>
    <nd ref="3490601193" lat="28.0396881" lon="85.1199142"/>
    <nd ref="3477698915" lat="28.0393977" lon="85.1199552"/>
    <nd ref="3477698914" lat="28.0390468" lon="85.1197873"/>
    <nd ref="3477698912" lat="28.0381188" lon="85.1194339"/>
    <nd ref="3488008881" lat="28.0378904" lon="85.1191959"/>
    <nd ref="3477698909" lat="28.0375339" lon="85.1188243"/>
    <nd ref="3490599865" lat="28.0373834" lon="85.1179659"/>
    <nd ref="3477698908" lat="28.0372922" lon="85.1174460"/>
    <nd ref="3477698907" lat="28.0370582" lon="85.1167480"/>
    <nd ref="3477698906" lat="28.0370582" lon="85.1157496"/>
    <nd ref="3477698904" lat="28.0367931" lon="85.1150605"/>
    <nd ref="3477698902" lat="28.0363564" lon="85.1147247"/>
    <nd ref="3477698899" lat="28.0356935" lon="85.1142918"/>
    <nd ref="3477698895" lat="28.0350852" lon="85.1140091"/>
    <nd ref="3477698893" lat="28.0345939" lon="85.1134083"/>
    <nd ref="3477698791" lat="28.0340870" lon="85.1121006"/>
    <nd ref="3477698790" lat="28.0338920" lon="85.1115087"/>
    <nd ref="3476578258" lat="28.0332632" lon="85.1110810"/>
    <nd ref="3476578248" lat="28.0329653" lon="85.1110523"/>
    <nd ref="3476578240" lat="28.0327117" lon="85.1110738"/>
    <nd ref="3476578232" lat="28.0324962" lon="85.1110523"/>
    <nd ref="3476578221" lat="28.0321412" lon="85.1107507"/>
    <nd ref="3476578216" lat="28.0319891" lon="85.1107004"/>
    <nd ref="3476578212" lat="28.0318623" lon="85.1108584"/>
    <nd ref="3476578206" lat="28.0317102" lon="85.1110523"/>
    <nd ref="3476578195" lat="28.0314947" lon="85.1112534"/>
    <nd ref="3476578197" lat="28.0315073" lon="85.1113683"/>
    <nd ref="3476578202" lat="28.0315961" lon="85.1114832"/>
    <nd ref="3476578200" lat="28.0315644" lon="85.1116483"/>
    <nd ref="3476578194" lat="28.0314820" lon="85.1118207"/>
    <nd ref="3476578188" lat="28.0313108" lon="85.1118351"/>
    <nd ref="3476578181" lat="28.0311524" lon="85.1119212"/>
    <nd ref="3476578176" lat="28.0309368" lon="85.1120290"/>
    <nd ref="3476578166" lat="28.0307150" lon="85.1122875"/>
    <nd ref="3476578161" lat="28.0306199" lon="85.1123665"/>
    <nd ref="3476578159" lat="28.0305565" lon="85.1124383"/>
    <nd ref="3476578153" lat="28.0304193" lon="85.1124956"/>
    <nd ref="3476578147" lat="28.0303464" lon="85.1124974"/>
    <nd ref="3476578142" lat="28.0302402" lon="85.1124650"/>
    <nd ref="3476578140" lat="28.0301753" lon="85.1124597"/>
    <nd ref="3476578135" lat="28.0300897" lon="85.1124776"/>
    <nd ref="3476578134" lat="28.0300421" lon="85.1125943"/>
    <nd ref="3476578130" lat="28.0299819" lon="85.1125943"/>
    <nd ref="3476578123" lat="28.0299059" lon="85.1125997"/>
    <nd ref="3476578117" lat="28.0298361" lon="85.1126859"/>
    <nd ref="3476578114" lat="28.0297680" lon="85.1127828"/>
    <nd ref="3476578111" lat="28.0297046" lon="85.1127918"/>
    <nd ref="3476578108" lat="28.0296222" lon="85.1127559"/>
    <nd ref="3476578102" lat="28.0295287" lon="85.1127272"/>
    <nd ref="3476578098" lat="28.0294495" lon="85.1126715"/>
    <nd ref="3476578092" lat="28.0293116" lon="85.1127218"/>
    <nd ref="3476578088" lat="28.0291674" lon="85.1127469"/>
    <nd ref="3476578082" lat="28.0290580" lon="85.1128313"/>
    <nd ref="3476578079" lat="28.0289915" lon="85.1129193"/>
    <nd ref="3476578077" lat="28.0289170" lon="85.1129641"/>
    <nd ref="3476578074" lat="28.0287950" lon="85.1129821"/>
    <nd ref="3476578072" lat="28.0286967" lon="85.1130144"/>
    <nd ref="3476578068" lat="28.0285620" lon="85.1131293"/>
    <nd ref="3476578064" lat="28.0284669" lon="85.1131203"/>
    <nd ref="3476578058" lat="28.0283179" lon="85.1130808"/>
    <nd ref="3476578056" lat="28.0282007" lon="85.1130754"/>
    <nd ref="3476578052" lat="28.0281357" lon="85.1131832"/>
    <nd ref="3476578051" lat="28.0280723" lon="85.1132316"/>
    <nd ref="3476578050" lat="28.0280343" lon="85.1131724"/>
    <nd ref="3476578048" lat="28.0280263" lon="85.1130593"/>
    <nd ref="3476578046" lat="28.0279661" lon="85.1130431"/>
    <nd ref="3476578037" lat="28.0278964" lon="85.1130790"/>
    <nd ref="3476578027" lat="28.0278061" lon="85.1130754"/>
    <nd ref="3476578025" lat="28.0276967" lon="85.1131508"/>
    <nd ref="3476578017" lat="28.0275874" lon="85.1131419"/>
    <nd ref="3476578013" lat="28.0274558" lon="85.1131526"/>
    <nd ref="3488830107"/>
    <nd ref="3488830106"/>
    <nd ref="3488830105"/>
    <nd ref="3488830104"/>
    <nd ref="3488830103"/>
    <nd ref="3477698777" lat="28.0272279" lon="85.1128781"/>
    <nd ref="3488836288"/>
    <nd ref="3488830108"/>
    <nd ref="3477698776" lat="28.0270524" lon="85.1124452"/>
    <nd ref="3488830102"/>
    <nd ref="3488014975" lat="28.0267980" lon="85.1121412"/>
    <nd ref="3477698775" lat="28.0267678" lon="85.1121051"/>
    <nd ref="3477698772" lat="28.0264792" lon="85.1119990"/>
    <nd ref="3477698769" lat="28.0260697" lon="85.1118886"/>
    <nd ref="3489310259" lat="28.0259030" lon="85.1117969"/>
    <nd ref="3477698767" lat="28.0258046" lon="85.1117428"/>
    <nd ref="3477698766" lat="28.0257255" lon="85.1116760"/>
    <tag k="highway" v="path"/>
  </way>
```

**Comment by malenki** [comment] 2015-05-03 18:19
So it seems we can only hope and pray there won't be too many
diff "glitches"…

**Comment by sletuffe** [comment] 2015-05-03 21:13
Thanks mmd that was quite a detective work !

The api.openstreetmap.fr was indeeded affected by this glitch and missing what was in that diff.
I've restarted applying diff from this one and the corresponding nodes seam to have been reimported.

However, the true nature of that "corrupt glitch" is still unknown to me and is quite likely to reappear. The only information I suspect is that during the import of the supposedly corrupted diff file, the update_database processus met an out of memory condition.
However, that is quite speculative as I don't keep older diffs and cannot check if what was downloaded at the time of the problem would cause another out of memory condition.

Next time I'll try to check a little more what was in that diff.

**Comment by mmd-osm** [comment] 2015-05-03 21:35
> The only information I suspect is that during the import of the supposedly corrupted diff file, the update_database processus met an out of memory condition.

It's all about the replication process on the OSM main server. Overpass API just processes what's in the minutely diffs directory at that time. Those files were ok and not corrupted in any way. There's also no out of memory condition whatsoever. The real trouble starts a bit later:

From time to time the replication process on the main server seems to hang and somehow needs to be restarted. During that restart process, some already written .osc.gz. files seem to be written a second time, this time with much more changesets in them. Overpass API won't pick up those newly written .osc.gz files and there you lose your changesets. I don't know if writing the same changeset files multiple times is ok. Right now, it just seems to occur once in a while.

Maybe @tomhughes has some explanation what is really going on here or how this situation could be avoided (or maybe at least detected) in the first place. Whatever makes most sense.

**Comment by tomhughes** [comment] 2015-05-03 21:37
It's pretty simple really, if you get a zero byte file then ignore it and keep retying it until you get a proper file.

**Comment by mmd-osm** [comment] 2015-05-03 21:41
@tomhughes : the first time, the file size was 48375 bytes. The very same file was later written with a filesize of 2.2M. Both versions look perfectly valid, can be gunzip'ed without any issue.

So checking for a zero byte file won't help here.

**Comment by tomhughes** [comment] 2015-05-03 21:43
Oh I know nothing about that then. 

I assume you were talking about the other day when the server crashed and left a zero byte file that hadn't been flushed, so I had to reset the state.

**Comment by tomhughes** [comment] 2015-05-03 21:46
Ah I guess maybe if you managed to download it before the server crashed then it might not have been zero sized... But after the server came back up it was because it had never been flushed before.

The real fix is to make omosis sync the files to disk properly, so  that's the place to look if you want to improve things.

**Comment by mmd-osm** [comment] 2015-05-03 21:53
Just as a reference: I put both versions on the dev server now: http://dev.overpass-api.de/issue210/defect/

**Comment by mmd-osm** [comment] 2015-05-04 17:50
> The real fix is to make omosis sync the files to disk properly, so that's the place to look if you want to improve things.

@tomhughes : I'm not exactly sure on how to get in touch with the right people. There's some osmosis-dev list around with very little traffic, and there's the [OSM trac](https://trac.openstreetmap.org/query?component=osmosis).

As I don't have access to the main OSM instance to collect further evidence (such as log files documenting the exact sequence of events before/during/after the hickup), would you mind creating a new ticket on trac with further details and link it here? That would really be terrific. I will of course add any insight I have from a data consumer point of view along with the implications on follow-on processes.

**Comment by tomhughes** [comment] 2015-05-04 18:02
Well I don't think osmosis has any real active maintenance at the moment and I certainly don't have any special evidence to offer.

**Comment by malenki** [comment] 2015-05-04 19:16
Thanks for digging into this issue so painstakingly.

**Comment by tomhughes** [comment] 2015-05-04 21:24
What the hell is that supposed to mean.

I've told you what I think happened. There are no logs that will, or ever could, confirm that theory. What exactly do you want me to do?

**Comment by tomhughes** [comment] 2015-05-04 21:32
If it makes you all happy I have raised https://trac.openstreetmap.org/ticket/5312 for you now.

**Comment by drolbr** [comment] 2015-05-05 19:11
I'm sorry for the late reply: I think I would like to also add protection mechanisms to the download process:

The update process should get resilient against applying the same update twice. After talking with lonvia at the FOSSGIS I would relize this by ignoring elements if an explicit version with a strictly newer timestamp of that element already exists.

The second protection should be to suspend updates and produce an alert if no new diffs get available within a certain time window (I think of half an hour or so).

The third protection mechanism is to make regular backups of the mirror database. Currently it is possible to catch up in about 30-fold real time. Hence, even a backup once a week would mean that under worst possible circumstances the mirror could catch up within 8 hours or so.

Please note that these protections are useful on their own. For example, the third one will mitigate any kind of accident, e.g. also a bit flip due to hardware problems. The first one will help when starting minutely updates from a fresh planet, because you can then safely start with some overlap without the risk of damaged data.

On the other hand: I appreciate very much Toms fast response. But controlling what is exactly happening in a crash-reboot-recover setting on a nontrivial system is close to impossible, because systems on other layers (the file system, the dbms, etc.) may have their own idea of consistent state and impose it at an uncoordinated point in time in an unexpected way. This is most likely a really tough bug there, but a manageable bug here. Hence we should fix it preferably  downstream.

**Comment by malenki** [comment] 2015-05-05 19:44
Tom Hughes wrote

> What the hell is that supposed to mean.

"Thank You"

> I've told you what I think happened. There are no logs that will, or
> ever could, confirm that theory. What exactly do you want me to do?

Nothing.

**Comment by mmd-osm** [comment] 2015-05-05 19:51
> I appreciate very much Toms fast response.
I second that. 

>This is most likely a really tough bug there, but a manageable bug here. Hence we should fix it preferably downstream.
The main reason why I was asking for this ticket is to have some awareness that this kind of issue in fact exists and possibly hits every minutely diff consuming application (not only Overpass API).

I'm perfectly fine with having additional checks on Overpass API. But what about other applications which might be affected in a similar way? If the osmosis developers later come back with "sorry, there's nothing we can do about it", then that's also perfectly fine. If they could do something about it, every data consumer in the OSM ecosystem would benefit.

**Comment by mmd-osm** [comment] 2016-02-12 12:32
FYI only

Issue reoccured today, see Rolands update on the dev ml: http://permalink.gmane.org/gmane.comp.gis.openstreetmap.overpass/220

**Comment by drolbr** [comment] 2016-08-18 05:32
I'm currently reviewing which bugs should be fixed in the next version. This bug won't, it is too complex. I'll shortly explain details:

The first protection is already effective for non-attic data provided that:
- all diffs up to the current diff have been applied at least once
- for each applied diff all later diffs have been applied after the last application of that diff
In the simple case that you recover from a hiccup like the one in question here by applying all diffs since and including the broken diff then the two conditions above are satisfied.

For attic data, the ramifications are much more difficult: until now, no attic data is ever deleted once it has been written. This cannot be upheld anymore if we want to be resilient in the told way. Thus, this has to be checked extra carefully to ensure that no data is lost. While it is technically possible, this is beyond little thing that can be fixed on the fly.

The second protection will be implemented in the course of this release preparation, see commit fd804d91aacdef19586b0bb94862cfcdf9ac86a2

The third is less a question of software and more a question of organzation. Shortly: we don't have enough disk space to automate this in a safe way. Hence, I will not promise this right now.

**Comment by drolbr** [comment] 2017-03-05 09:57
The last part of the issue is solved by an automatic daily cloning.

**Closed by drolbr** 2017-03-05 09:57 UTC
Labels: bug
